name: PyTest

on: [push]

jobs:
  make-testing:
    name: PyTest checking
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Building project
        uses: ./.github/actions/build

      - name: Checking
        run:  ls src/test_*.py 2> /dev/null && python3 -m pytest src
        shell: bash
