name: Test get-subseqs tool

on: [push]

jobs:
  testing:
    name: Test get-subseqs tool
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Building project
        uses: ./.github/actions/build

      - name: Running test
        run:  ./test-get-subseqs.sh
        shell: bash
